<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Create' => 'Cadastrar',
    'Create Aluno' => 'Cadastrar Aluno',
    'Create Alunos' => 'Cadastrar Alunos',
    'Create Professor' => 'Cadastrar Professor',
    'Create Disciplina' => 'Cadastrar Disciplina',
    'Create Aluno Matriculado' => 'Cadastrar Aluno',
    'Create Documento Oficial' =>'Emitir documento',
    'Create Frequencia' => 'Frequências',
    'Create Frequencia Rendimento' => 'Rendimentos',
    'Create Conteudo Ministrado' => 'Conteúdo Ministrado',
    'Create Mapa Geral' => 'Mapa Geral',
    'Create {var}' => 'Cadastrar {var}',
    'Delete' => 'Excluir',
    'Name' => '',
    'Reset' => 'Limpar',
    'Search' => 'Buscar',
    'Send mail' => 'Enviar e-mail',
    'Submit' => '',
    'Update' => 'Alterar',
    'Update {modelClass}: ' => 'Alterar {modelClass}: ',
    'Create Usuario' => 'Cadastrar Usuario',
    'Create Relatorio' => 'Cadastrar Relatório',
    'Save' => 'Salvar',
    'Events' => 'Eventos',
    'Create Event' => 'Cadastrar Eventos',
    'Create Turma' => 'Cadastrar Turma',
    'Formacao'=> 'Formação',
    'Turma ID' => 'Turma',
    'Professors' => 'Professores',
    'Create Aula' => 'Cadastrar Aula',
    'Create Turma Infantil' => 'Cadastrar Turma Infantil',
    'Turmas Infantils' => 'Turmas Infantis',
    'Create Diagnostico Inicial' => 'Cadastrar Diagnóstico Inicial',
    'Create Livro Controle' => 'Registrar Transferência',
    'Classificacao ID' => 'Classificacão',
    'Create Editora' => 'Cadastrar Editora',
    'Locacaos' => 'Locação',
    'Create Locacao' => 'Registrar Locação',
    'Create Reserva' => 'Registrar Reserva',
    'Create Livro' => 'Cadastrar Livro',
    'Create Autor' => 'Cadastrar Autor',
    'Create Classificacao' => 'Cadastrar Classificação',
    'Classificacao' => 'Classificação',
    'Datahorareserva' => 'Dia da Reserva',
    'Aluno ID' => 'Aluno',
    'Livro ID' => 'Livro',
    'Update Reserva' => 'Modificar Reserva',
    'Professors' => 'Professores',
    'Create Eventos' => 'Cadastrar Eventos',
    'Event' => 'Evento',
    'Create Projeto' => 'Cadastrar Projetos'
        ];
